### ISSUE TITLE
"uboot printenv" does not work on all devices - IPC-HDW1430 

### ISSUE THREAD

**Issue by kuzco1** [mcw0/DahuaConsole#33]
I am using this tool since month for many IPC, VTH and also VTO.
However, I have a new IPC (HDW1430DT-STW / IPC-WDX2) which has some issues with this script.
The login with "./Console.py --rhost 192.168.178.241 --auth admin:kennwort" works fine. The command "device" works also fine, but commands "uboot printenv", "service" or "config all" does not work.

[Console]# uboot printenv
Traceback (most recent call last):
  File "/root/220723_DahuaConsole/./Console.py", line 888, in <module>
    main()
  File "/root/220723_DahuaConsole/./Console.py", line 882, in main
    DebugConsole(dargs=dargs)
  File "/root/220723_DahuaConsole/./Console.py", line 32, in __init__
    self.main_console()
  File "/root/220723_DahuaConsole/./Console.py", line 243, in main_console
    exec(tmp)
  File "<string>", line 1, in <module>
  File "/root/220723_DahuaConsole/dahua.py", line 1396, in u_boot
    self.instance_service(method_name, start=True)
  File "/root/220723_DahuaConsole/net.py", line 907, in instance_service
    if not self.check_for_service(method_name):
  File "/root/220723_DahuaConsole/net.py", line 1165, in check_for_service
    if not len(self.RemoteServicesCache):
TypeError: object of type 'bool' has no len()

[Console]# service
Traceback (most recent call last):
  File "/root/220723_DahuaConsole/./Console.py", line 888, in <module>
    main()
  File "/root/220723_DahuaConsole/./Console.py", line 882, in main
    DebugConsole(dargs=dargs)
  File "/root/220723_DahuaConsole/./Console.py", line 32, in __init__
    self.main_console()
  File "/root/220723_DahuaConsole/./Console.py", line 243, in main_console
    exec(tmp)
  File "<string>", line 1, in <module>
  File "/root/220723_DahuaConsole/dahua.py", line 97, in list_service
    self.check_for_service('dump')
  File "/root/220723_DahuaConsole/net.py", line 1165, in check_for_service
    if not len(self.RemoteServicesCache):
TypeError: object of type 'bool' has no len()

[Console]# config all
[-] [config_members] Error: {'code': 268959743, 'message': 'Unknown error! error code was not set in service!'}

Have also checked the requirements again:
root@camserver:~/220723_DahuaConsole# sudo pip3 install -r requirements.txt
Requirement already satisfied: pwntools>=4.3.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 1)) (4.9.0)
Requirement already satisfied: ndjson>=0.3.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 2)) (0.3.1)
Requirement already satisfied: pycryptodome>=3.9.7 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 3)) (3.10.4)
Requirement already satisfied: tzlocal>=2.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 4)) (4.2)
Requirement already satisfied: pyOpenSSL>=19.1.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 5)) (21.0.0)
Requirement already satisfied: requests>=2.20.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 6)) (2.25.1)
Requirement already satisfied: pwn~=1.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 7)) (1.0)
Requirement already satisfied: paramiko>=1.15.2 in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (2.7.2)
Requirement already satisfied: mako>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (1.1.5)
Requirement already satisfied: pyelftools>=0.2.4 in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (0.27)
Requirement already satisfied: capstone>=3.0.5rc2 in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: ropgadget>=5.3 in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (6.6)
Requirement already satisfied: pyserial>=2.7 in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (3.5)
Requirement already satisfied: pip>=6.0.8 in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (23.1.1)
Requirement already satisfied: pygments>=2.0 in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (2.10.0)
Requirement already satisfied: pysocks in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (1.7.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (21.0)
Requirement already satisfied: psutil>=3.3.0 in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (5.8.0)
Requirement already satisfied: intervaltree>=3.0 in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: unicorn>=1.0.2rc1 in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (1.0.2rc3)
Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: rpyc in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (5.0.1)
Requirement already satisfied: colored-traceback in /usr/local/lib/python3.9/dist-packages (from pwntools>=4.3.1->-r requirements.txt (line 1)) (0.3.0)
Requirement already satisfied: pytz-deprecation-shim in /usr/local/lib/python3.9/dist-packages (from tzlocal>=2.1->-r requirements.txt (line 4)) (0.1.0.post0)
Requirement already satisfied: cryptography>=3.3 in /usr/local/lib/python3.9/dist-packages (from pyOpenSSL>=19.1.0->-r requirements.txt (line 5)) (35.0.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.9/dist-packages (from cryptography>=3.3->pyOpenSSL>=19.1.0->-r requirements.txt (line 5)) (1.14.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.9/dist-packages (from mako>=1.0.0->pwntools>=4.3.1->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.9/dist-packages (from paramiko>=1.15.2->pwntools>=4.3.1->-r requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from paramiko>=1.15.2->pwntools>=4.3.1->-r requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.9/dist-packages (from packaging->pwntools>=4.3.1->-r requirements.txt (line 1)) (2.4.7)
Requirement already satisfied: tzdata in /usr/local/lib/python3.9/dist-packages (from pytz-deprecation-shim->tzlocal>=2.1->-r requirements.txt (line 4)) (2022.1)
Requirement already satisfied: plumbum in /usr/local/lib/python3.9/dist-packages (from rpyc->pwntools>=4.3.1->-r requirements.txt (line 1)) (1.7.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/dist-packages (from cffi>=1.12->cryptography>=3.3->pyOpenSSL>=19.1.0->-r requirements.txt (line 5)) (2.20)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by mcw0** [comment]
I think this is one of the drawbacks for using not official supported APIs...
